import type { Metadata } from "next";
import { Geist, Geist_Mono, Newsreader   } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const newsreader = Newsreader({
  subsets: ["latin"],
  weight: ["400", "500", "700", "800"], 
  variable: "--font-pre-newsreader", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${newsreader.variable}antialiased`}
      >
        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
